// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-G79VL28eXUd1I4KflF42dDdv1R01tk',
    appId: '1:443591797148:android:2ae1ce3d06fbe706e50059',
    messagingSenderId: '443591797148',
    projectId: 'deukarten-e71c7',
    databaseURL: 'https://deukarten-e71c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deukarten-e71c7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB47cMi6RgQPcq-sxAFi-bS6w9XClvhdes',
    appId: '1:443591797148:web:6638d4739a797559e50059',
    messagingSenderId: '443591797148',
    projectId: 'deukarten-e71c7',
    authDomain: 'deukarten-e71c7.firebaseapp.com',
    databaseURL: 'https://deukarten-e71c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deukarten-e71c7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0fDQ2TP1AfqfSI5Bgyb8bwCci6gCNfpU',
    appId: '1:443591797148:ios:70bd0a0957ba25efe50059',
    messagingSenderId: '443591797148',
    projectId: 'deukarten-e71c7',
    databaseURL: 'https://deukarten-e71c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deukarten-e71c7.firebasestorage.app',
    iosClientId: '443591797148-aj3ucmna95lcd642e1jkgsj2v0944n6p.apps.googleusercontent.com',
    iosBundleId: 'com.deukarten.deuKarten',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0fDQ2TP1AfqfSI5Bgyb8bwCci6gCNfpU',
    appId: '1:443591797148:ios:70bd0a0957ba25efe50059',
    messagingSenderId: '443591797148',
    projectId: 'deukarten-e71c7',
    databaseURL: 'https://deukarten-e71c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deukarten-e71c7.firebasestorage.app',
    iosClientId: '443591797148-aj3ucmna95lcd642e1jkgsj2v0944n6p.apps.googleusercontent.com',
    iosBundleId: 'com.deukarten.deuKarten',
  );

}